# Generated by Django 3.2.3 on 2021-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeCrossWalk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosswalk',
            old_name='gyeondo',
            new_name='gyeongdo',
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='has_trlight',
            field=models.BooleanField(default=True),
        ),
    ]
