# Generated by Django 3.2.3 on 2021-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeCrossWalk', '0002_auto_20210522_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='crosswalk',
            old_name='gyeongdo',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='crosswalk',
            old_name='wuido',
            new_name='lon',
        ),
        migrations.AddField(
            model_name='drivers',
            name='brake',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='curlat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='curlon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='is_incoming',
            field=models.BooleanField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='prevlat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='prevlon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivers',
            name='signal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
